services:
  pronghorn-api:
    build:
      context: .
      dockerfile: production.prongapi.containerfile
    environment:
      APPLICATION_URL: ${APPLICATION_URL}
      SECRET_KEY: ${SECRET_KEY}
      VALKEY_HOST: ${VALKEY_HOST}
      VALKEY_PASS: ${VALKEY_PASS}
      AWS_ENDPOINT_URL_S3: ${AWS_ENDPOINT_URL_S3}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS} 
      DB_NAME: ${DB_NAME}
      SESSION_REDIS: ${SESSION_REDIS}
    ports:
      - "8000:8000"
    networks: 
      - pronghorn_app_network 
  valkey:
    container_name: prong-valkey
    image: docker.io/valkey/valkey:8.1.1
    healthcheck:
      test: valkey-cli ping || exit 1
    restart: always
    command: valkey-server --requirepass ${VALKEY_PASS}
    networks: 
      - pronghorn_app_network 
  web-app:
    build:
      context: .
      dockerfile: production.prongwebapp.containerfile
    ports:
      # - "80:80"
      # - "443:443"
      - "6900:6900"
    networks: 
      - pronghorn_app_network
    volumes:
      - nginx_conf:/etc/nginx/
      - nginx_certs:/etc/ssl/

  # Postgres database, uncomment if not using external database host
  # db:
  #   container_name: postgres_container
  #   image: postgres
  #   restart: always
  #   environment:
  #     POSTGRES_USER: root
  #     POSTGRES_PASSWORD: $(DB_ROOT_PASS)
  #     POSTGRES_DB: annotation_db
  #   volumes:
  #     - $(DB_STORAGE):/var/lib/postgresql/data
  #   networks:
  #     - pronghorn_app_network
  #   ports:
  #     - "5432:5432"
  #   user: "999:999"

volumes:
  nginx_conf:
  nginx_certs:

networks: 
  pronghorn_app_network:
    driver: bridge