CREATE SCHEMA "core";
CREATE SCHEMA "usermanagement";
CREATE SCHEMA "projectmanagement";

-- CORE SCHEMA
CREATE TABLE "core"."images" (
  "image_id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "survey_id" integer NOT NULL DEFAULT 0,
  "herd_unit_id" integer NOT NULL DEFAULT 0,
  "name" varchar(50) NOT NULL,
  "img_key" varchar(200) UNIQUE NOT NULL,
  "in_training" boolean DEFAULT false,
  "crops_generated" smallint DEFAULT 0,
  "opened_by_user_id" integer NOT NULL DEFAULT 0,
  "created" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "modified" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "image_length_px" integer NOT NULL,
  "image_width_px" integer NOT NULL,
  "area" float,
  "viewshed_polygon" point[],
  "has_detection" boolean,
  "dem_name" varchar(36),
  "bbox_wsen" integer[],
  "uuid" uuid UNIQUE NOT NULL DEFAULT gen_random_uuid()
);

CREATE TABLE "core"."predictions" (
  "pred_id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "image_id" integer NOT NULL,
  "model_id" integer NOT NULL DEFAULT 0,
  "reviewed_by_user_id" integer NOT NULL DEFAULT 0,
  "label" integer NOT NULL,
  "score" double precision NOT NULL,
  "box_tx" integer NOT NULL,
  "box_ty" integer NOT NULL,
  "box_bx" integer NOT NULL,
  "box_by" integer NOT NULL,
  "created" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "uuid" uuid UNIQUE NOT NULL DEFAULT gen_random_uuid()
);

CREATE TABLE "core"."reviewed_area" (
  "reviewed_area_id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "image_id" integer NOT NULL,
  "name" varchar(100) NOT NULL,
  "ra_key" varchar(200) UNIQUE NOT NULL,
  "area_tx" integer NOT NULL,
  "area_ty" integer NOT NULL,
  "area_bx" integer NOT NULL,
  "area_by" integer NOT NULL,
  "reviewed_area_length_px" integer NOT NULL DEFAULT 2100,
  "reviewed_area_width_px" integer NOT NULL DEFAULT 2100,
  "reviewed_by_user_id" integer NOT NULL DEFAULT 0,
  "created" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "modified" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "uuid" uuid UNIQUE NOT NULL DEFAULT gen_random_uuid()
);

CREATE TABLE "core"."annotations" (
  "annotation_id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "label_id" integer NOT NULL DEFAULT 0,
  "image_id" integer NOT NULL DEFAULT 0,
  "pred_id" integer NOT NULL,
  "herd_unit_id" integer NOT NULL DEFAULT 0,
  "box_tx" integer NOT NULL,
  "box_ty" integer NOT NULL,
  "box_bx" integer NOT NULL,
  "box_by" integer NOT NULL,
  "created_by_user_id" integer NOT NULL,
  "created" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "modified" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "uuid" uuid UNIQUE NOT NULL DEFAULT gen_random_uuid()
);

-- USER MANAGEMENT SCHEMA
CREATE TABLE "usermanagement"."users" (
  "user_id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "default_org_id" integer NOT NULL DEFAULT 0,
  "username" varchar(20) NOT NULL,
  "email" varchar(320) UNIQUE NOT NULL,
  "password_hash" varchar(255),
  "external_auth_id" varchar(255),
  "external_auth_provider" varchar(50),
  "status" varchar(20) NOT NULL DEFAULT 'invited',
  "created" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "modified" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "last_login" timestamptz,
  "locale" varchar(10),
  "uuid" uuid UNIQUE NOT NULL DEFAULT gen_random_uuid()
);

CREATE TABLE "usermanagement"."roles" (
  "role_id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(25) UNIQUE NOT NULL,
  "created" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "modified" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "uuid" uuid UNIQUE NOT NULL DEFAULT gen_random_uuid()
);

CREATE TABLE "usermanagement"."organizations" (
  "organization_id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50) UNIQUE NOT NULL,
  "logo_url" varchar(1000),
  "created" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "modified" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "uuid" uuid UNIQUE NOT NULL DEFAULT gen_random_uuid()
);

-- PROJECT MANAGEMENT SCHEMA
CREATE TABLE "projectmanagement"."projects" (
  "project_id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50) NOT NULL,
  "created" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "modified" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "uuid" uuid UNIQUE NOT NULL DEFAULT gen_random_uuid()
);

CREATE TABLE "projectmanagement"."schemas" (
  "schema_id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(30) NOT NULL,
  "created" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "modified" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "uuid" uuid UNIQUE NOT NULL DEFAULT gen_random_uuid()
);

CREATE TABLE "projectmanagement"."labels" (
  "label_id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "schema_id" integer NOT NULL DEFAULT 0,
  "label" smallint NOT NULL,
  "name" varchar(50) NOT NULL,
  "created" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "modified" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "uuid" uuid UNIQUE NOT NULL DEFAULT gen_random_uuid()
);

CREATE TABLE "projectmanagement"."herd_units" (
  "herd_unit_id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(30) NOT NULL,
  "created" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "modified" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "uuid" uuid UNIQUE NOT NULL DEFAULT gen_random_uuid()
);

CREATE TABLE "projectmanagement"."models" (
  "model_id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "schema_id" integer NOT NULL DEFAULT 0,
  "name" varchar(30) NOT NULL,
  "created" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "modified" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "uuid" uuid UNIQUE NOT NULL DEFAULT gen_random_uuid()
);

CREATE TABLE "projectmanagement"."surveys" (
  "survey_id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50),
  "created" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "modified" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "uuid" uuid UNIQUE NOT NULL DEFAULT gen_random_uuid()
);

CREATE TABLE "usermanagement"."initialization" (
  "init_id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "first_run" boolean NOT NULL DEFAULT true
);

-- JUNCTION TABLES
CREATE TABLE "core"."training" ("reviewed_area_id" integer, "model_id" integer, PRIMARY KEY ("reviewed_area_id", "model_id"));
CREATE TABLE "core"."annotations_reviewed_area" ("annotation_id" integer, "reviewed_area_id" integer, PRIMARY KEY ("annotation_id", "reviewed_area_id"));
CREATE TABLE "usermanagement"."organizations_projects" ("project_id" integer, "organization_id" integer, PRIMARY KEY ("project_id", "organization_id"));
CREATE TABLE "usermanagement"."organizations_users" ("user_id" integer, "organization_id" integer, "role_id" integer, PRIMARY KEY ("user_id", "organization_id", "role_id"));
CREATE TABLE "projectmanagement"."projects_users" ("project_id" integer, "user_id" integer, "role_id" integer, PRIMARY KEY ("project_id", "user_id", "role_id"));
CREATE TABLE "projectmanagement"."projects_schemas" ("project_id" integer, "schema_id" integer, PRIMARY KEY ("project_id", "schema_id"));
CREATE TABLE "projectmanagement"."projects_herd_units" ("project_id" integer, "herd_unit_id" integer, PRIMARY KEY ("project_id", "herd_unit_id"));
CREATE TABLE "projectmanagement"."projects_models" ("project_id" integer, "model_id" integer, PRIMARY KEY ("project_id", "model_id"));
CREATE TABLE "projectmanagement"."surveys_models" ("survey_id" integer, "model_id" integer, PRIMARY KEY ("survey_id", "model_id"));
CREATE TABLE "projectmanagement"."herd_units_models" ("herd_unit_id" integer, "model_id" integer, PRIMARY KEY ("herd_unit_id", "model_id"));
CREATE TABLE "projectmanagement"."projects_surveys" ("survey_id" integer, "project_id" integer, PRIMARY KEY ("survey_id", "project_id"));
CREATE TABLE "projectmanagement"."surveys_herd_units" ("survey_id" integer, "herd_unit_id" integer, PRIMARY KEY ("survey_id", "herd_unit_id"));

CREATE UNIQUE INDEX ON "core"."images" ("herd_unit_id", "name");

CREATE INDEX ON "core"."images" ("created");

CREATE INDEX ON "core"."images" ("uuid");

CREATE INDEX ON "core"."images" ("survey_id");

CREATE INDEX ON "core"."predictions" ("label");

CREATE INDEX ON "core"."predictions" ("score");

CREATE INDEX ON "core"."predictions" ("model_id");

CREATE INDEX ON "core"."predictions" ("reviewed_by_user_id");

CREATE INDEX ON "core"."predictions" ("image_id");

CREATE INDEX ON "core"."predictions" ("created");

CREATE INDEX ON "core"."predictions" ("uuid");

CREATE INDEX ON "core"."reviewed_area" ("image_id");

CREATE INDEX ON "core"."reviewed_area" ("created");

CREATE INDEX ON "core"."reviewed_area" ("reviewed_area_length_px", "reviewed_area_width_px");

CREATE INDEX ON "core"."reviewed_area" ("uuid");

CREATE INDEX ON "core"."annotations" ("label_id");

CREATE INDEX ON "core"."annotations" ("image_id");

CREATE INDEX ON "core"."annotations" ("uuid");

CREATE INDEX ON "core"."annotations" ("created");

CREATE INDEX ON "usermanagement"."users" ("status");

CREATE INDEX ON "usermanagement"."users" ("modified");

CREATE INDEX ON "usermanagement"."users" ("last_login");

CREATE INDEX ON "usermanagement"."users" ("locale");

CREATE INDEX ON "usermanagement"."users" ("uuid");

CREATE INDEX ON "usermanagement"."roles" ("name");

CREATE INDEX ON "usermanagement"."roles" ("uuid");

CREATE INDEX ON "usermanagement"."roles" ("created");

-- Ensure only one root user exists
CREATE UNIQUE INDEX single_super_user_idx 
ON usermanagement.organizations_users (role_id) 
WHERE role_id = 1;

CREATE INDEX ON "usermanagement"."organizations" ("name");

CREATE INDEX ON "usermanagement"."organizations" ("uuid");

CREATE INDEX ON "usermanagement"."organizations" ("created");

CREATE INDEX ON "projectmanagement"."projects" ("name");

CREATE INDEX ON "projectmanagement"."projects" ("created");

CREATE INDEX ON "projectmanagement"."projects" ("uuid");

CREATE INDEX ON "projectmanagement"."schemas" ("name");

CREATE INDEX ON "projectmanagement"."schemas" ("created");

CREATE INDEX ON "projectmanagement"."schemas" ("uuid");

CREATE UNIQUE INDEX ON "projectmanagement"."labels" ("schema_id", "label");

CREATE INDEX ON "projectmanagement"."labels" ("uuid");

CREATE INDEX ON "projectmanagement"."labels" ("created");

CREATE INDEX ON "projectmanagement"."herd_units" ("name");

CREATE INDEX ON "projectmanagement"."herd_units" ("uuid");

CREATE INDEX ON "projectmanagement"."herd_units" ("created");

CREATE INDEX ON "projectmanagement"."models" ("name");

CREATE INDEX ON "projectmanagement"."models" ("schema_id");

CREATE INDEX ON "projectmanagement"."models" ("uuid");

CREATE INDEX ON "projectmanagement"."models" ("created");

CREATE INDEX ON "projectmanagement"."surveys" ("name");

CREATE INDEX ON "projectmanagement"."surveys" ("uuid");

CREATE INDEX ON "projectmanagement"."surveys" ("created");

-- 1. BASE ENTITIES
INSERT INTO usermanagement.users (user_id, username, email, status, created, modified) 
VALUES (0, 'NO_USER', 'none@system.local', 'DISABLED', now(), now());

INSERT INTO usermanagement.roles (role_id, name) 
VALUES (0, 'NO_ROLE');

INSERT INTO usermanagement.roles (name)
VALUES ('root');

INSERT INTO usermanagement.roles (name)
VALUES ('admin');

INSERT INTO usermanagement.roles (name)
VALUES ('annotator');

INSERT INTO usermanagement.organizations (organization_id, name) 
VALUES (0, 'NO_ORGANIZATION');

INSERT INTO usermanagement.organizations (name)
VALUES ('Root');

INSERT INTO projectmanagement.projects (project_id, name) 
VALUES (0, 'NO_PROJECT');

INSERT INTO projectmanagement.schemas (schema_id, name) 
VALUES (0, 'NO_SCHEMA');

INSERT INTO projectmanagement.labels (label_id, label, name) 
VALUES (0, -9999, 'NO_LABEL');

INSERT INTO projectmanagement.herd_units (herd_unit_id, name) 
VALUES (0, 'NO_HERD_UNIT');

INSERT INTO projectmanagement.models (model_id, name) 
VALUES (0, 'NO_MODEL');

INSERT INTO projectmanagement.surveys (survey_id, name) 
VALUES (0, 'NO_SURVEY');

-- 2. CORE PLACEHOLDERS 
INSERT INTO core.images (image_id, name, img_key, created, modified, image_length_px, image_width_px)
VALUES (0, 'NO_IMAGE', 'NONE', now(), now(), 0, 0);

INSERT INTO core.predictions (pred_id, image_id, label, score, box_tx, box_ty, box_bx, box_by, created)
VALUES (0, 0, 0, 0.0, 0, 0, 0, 0, now());

INSERT INTO core.reviewed_area (reviewed_area_id, image_id, name, ra_key, area_tx, area_ty, area_bx, area_by, created, modified)
VALUES (0, 0, 'NO_AREA', 'NONE', 0, 0, 0, 0, now(), now());

INSERT INTO core.annotations (annotation_id, pred_id, box_tx, box_ty, box_bx, box_by, created_by_user_id, created, modified)
VALUES (0, 0, 0, 0, 0, 0, 0, now(), now());


INSERT INTO usermanagement.organizations_projects (project_id, organization_id) VALUES (0, 0);
INSERT INTO usermanagement.organizations_users (user_id, organization_id, role_id) VALUES (0, 0, 0);
INSERT INTO projectmanagement.projects_users (project_id, user_id, role_id) VALUES (0, 0, 0);
INSERT INTO projectmanagement.projects_schemas (project_id, schema_id) VALUES (0, 0);
INSERT INTO projectmanagement.projects_herd_units (project_id, herd_unit_id) VALUES (0, 0);
INSERT INTO projectmanagement.projects_models (project_id, model_id) VALUES (0, 0);
INSERT INTO projectmanagement.surveys_models (survey_id, model_id) VALUES (0, 0);
INSERT INTO projectmanagement.herd_units_models (herd_unit_id, model_id) VALUES (0, 0);
INSERT INTO projectmanagement.projects_surveys (survey_id, project_id) VALUES (0, 0);
INSERT INTO projectmanagement.surveys_herd_units (survey_id, herd_unit_id) VALUES (0, 0);
INSERT INTO core.training (reviewed_area_id, model_id) VALUES (0, 0);
INSERT INTO core.annotations_reviewed_area (annotation_id, reviewed_area_id) VALUES (0, 0);
INSERT INTO usermanagement.initialization (first_run) VALUES (true);

